import 'dart:convert';
import 'package:cloud_firestore/cloud_firestore.dart';

class Task {
  /// **********************************************
  /// * Properties
  /// **********************************************

  /// A unique identifier that is automatically
  /// generated by Firebase.
  final String? id;

  /// The user ID that was generated by Firebase.
  final String uid;

  /// Name of the task.
  String title;

  /// What is the task all about?
  String description;

  /// The progress of the task.
  ///
  /// The available options are: `Not Started`,
  /// `In Progress`, and `Completed`.
  String status;

  /// The due date of a specific task.
  Timestamp deadline;

  /// Contains the name of the editor and
  /// the timestamp of the last edit.
  Map<String, dynamic> editor;

  /// **********************************************
  /// * Constructor
  /// **********************************************
  Task(
      {this.id,
      required this.uid,
      required this.title,
      required this.description,
      required this.status,
      required this.deadline,
      required this.editor});

  /// Instantiate [Task] from [JSON] format.
  factory Task.fromJson(Map<String, dynamic> json) {
    return Task(
        id: json['id'],
        uid: json['uid'],
        title: json['title'],
        description: json['description'],
        status: json['status'],
        deadline: json['deadline'],
        editor: json['editor']);
  }

  /// Convert each entry of [JSON] format
  /// into [Task] object.
  static List<Task> fromJsonArray(String jsonData) {
    final Iterable<dynamic> data = jsonDecode(jsonData);
    return data.map<Task>((dynamic d) => Task.fromJson(d)).toList();
  }

  /// Convert [Task] data into [JSON] format.
  Map<String, dynamic> toJson(Task task) {
    return {
      'id': task.id,
      'uid': task.uid,
      'title': task.title,
      'description': task.description,
      'status': task.status,
      'deadline': task.deadline,
      'editor': task.editor
    };
  }
}
