import 'dart:convert';
import 'package:cloud_firestore/cloud_firestore.dart';

class User {
  /// **********************************************
  /// * Properties
  /// **********************************************

  /// A unique identifier that is automatically
  /// generated by Firebase.
  final String? id;

  /// A unique identifier from the user.
  final String username;

  /// A unique identifier from the user.
  final String email;

  /// The display name of the user.
  String firstName;
  String lastName;

  /// The birthday of the user.
  Timestamp birthdate;

  /// The user's location is only limited
  /// to their country.
  String country;

  /// The biography will only be limited
  /// to 100 characters.
  String biography;

  /// Contains the user's friends. (UIDs)
  List<dynamic> friends;

  /// Contains the friend requests (UIDs)
  /// received by the user.
  List<dynamic> receivedRequests;

  /// Contains the friend requests (UIDs)
  /// sent by the user.
  List<dynamic> sentRequests;

  /// **********************************************
  /// * Constructor
  /// **********************************************
  User(
      {this.id,
      required this.username,
      required this.email,
      required this.firstName,
      required this.lastName,
      required this.birthdate,
      required this.country,
      required this.biography,
      required this.friends,
      required this.receivedRequests,
      required this.sentRequests});

  /// Instantiate [User] from [JSON] format.
  factory User.fromJson(Map<String, dynamic> json) {
    return User(
        id: json['id'],
        username: json['username'],
        email: json['email'],
        firstName: json['firstName'],
        lastName: json['lastName'],
        birthdate: json['birthdate'],
        country: json['country'],
        biography: json['biography'],
        friends: json['friends'],
        receivedRequests: json['receivedRequests'],
        sentRequests: json['sentRequests']);
  }

  /// Convert each entry of [JSON] format
  /// into [User] object.
  static List<User> fromJsonArray(String jsonData) {
    final Iterable<dynamic> data = jsonDecode(jsonData);
    return data.map<User>((dynamic d) => User.fromJson(d)).toList();
  }

  /// Convert [User] data into [JSON] format.
  Map<String, dynamic> toJson(User user) {
    return {
      'id': user.id,
      'username': user.username,
      'email': user.email,
      'firstName': user.firstName,
      'lastName': user.lastName,
      'birthdate': user.birthdate,
      'country': user.country,
      'biography': user.biography,
      'friends': user.friends,
      'receivedRequests': user.receivedRequests,
      'sentRequests': user.sentRequests
    };
  }
}
